# Generated by Django 4.1.3 on 2022-11-08 14:24

import contacts_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('twitter_handle', models.CharField(blank=True, max_length=250)),
                ('avatar_url', models.TextField(blank=True)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to=contacts_book.models.user_directory_path)),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
