# Generated by Django 4.1.3 on 2022-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_book', '0002_alter_contact_first_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
